### ISSUE TITLE
End of Game Play v2

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#104]
After round 8 - they can click a button that says finish game and it automatically plays to round 14, with no new actions being selected. Unsure if gremlins still come into play.

**Comment by Xiphe** [comment]
Ok, do I understand correctly? This is a derivation from https://github.com/mlevison/high-performance-teams-game/issues/90 where the three trailing rounds are not executed manual but automatically right?

**Comment by Xiphe** [comment]
Ah. It's an additional button? 

After round 8, the player can decide to click "next round" or "finish game"?

If yes, should we allow clicking next-round until round 14?

**Comment by mlevison** [comment]
Either that or after round 10, simply autoplay to 14. - Mark
