### ISSUE TITLE
Does drag effects always just remove 1 cap?

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#11]
From reading the rules i'm not sure how technical and communication drag effects are to be handled.

Given I take no actions at all and no special effects and gremlins come into play
And in round 1 I have a capacity of 10
And in round 2 I have a capacity of 9
Would I have a capacity of __9 or 8__ in round __3__?

**Comment by mlevison** [comment]
It decrements -1 per round until halted

round 3 - 8
round 4 - 7

Its funny we lost this detail in the OO version of the tests we deleted from before.

**Comment by Xiphe** [comment]
Oh! you're right it's stated here: https://github.com/mlevison/high-performance-teams-game/blob/object-oriented-approach/src/gameState/gameSamplePlays.spec.ts#L16-L32 😅

**Comment by Xiphe** [comment]
Closing since it's implemented and tested this way. I was just unsure as i've written the description in the text-rules.
