### ISSUE TITLE
Gremlins - protective actions taken after the incident shouldn't solve the problem

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#113]
Example: Gremlin - Management Yells. Next round the player selects Protected From Outside Distraction. The protective effect shouldn't happen because the action was taken after the fact.

Test code to prove the problem:

```ts
it('adding protected by outside distractions after the fact has no effect', () => {
      const game = getGame();

      game.nextRound('GREMLIN_MANAGEMENT_YELLS');
      testCurrentRound(game, { capacityChange: -2, userStoryChange: 0 });
      game.selectAction('PROTECTED_FROM_OUTSIDE_DISTRACTION');

      testFutureRounds(game, [
        { capacityChange: -2, userStoryChange: 0 },
        { capacityChange: -2, userStoryChange: 0 },
      ]);
    });`
```

I've checked in the same failing test.

-
I suspect this is a real challenge because the gremlin mechanism doesn't make it easy/possible to look up when an action was first applied and it that was before the gremlin.

**Comment by Xiphe** [comment]
Yeah, currently this is not possible, but we have that info. – It needs to be passed to the gremlin though.

Will do this after https://github.com/mlevison/high-performance-teams-game/pull/114
