### ISSUE TITLE
Simulation Poor game was impossible....

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#121]
...the poor game I saw in my first run of 1000 showed that in the first two rounds the player took no action. Since every round they should take three this shouldn't happen.

**Comment by Xiphe** [comment]
Oh, I might have checked in the wrong decision maker

Currently it uses `byChance` which uses a 35% chance to go to next round with each decision.



You can change it by setting it to `always3` in [`src/simulate/index.ts#L85`](https://github.com/mlevison/high-performance-teams-game/blob/main/src/simulate/index.ts#L85)

While you're at it, you could also try `byPercent` which takes ~30% capacity each round for improvements. You can also play with the percentage in [src/simulate/index.ts#L53](https://github.com/mlevison/high-performance-teams-game/blob/main/src/simulate/index.ts#L53)
