### ISSUE TITLE
Move Previous rounds actions are still available

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#124]
Move (and slightly change wording) of the "Previous rounds actions are still available to you to Select. Click the ► to open prior rounds.” line to below the current round actions and above the previous rounds.

**Comment by mlevison** [comment]
@Xiphe I can find the text in Actions.tsx.

What I can't see is how to add a mix of JavaScript/React to display the text. 

Is this reasonably easy?
If not how would I suppress the message in the first round? _Now I've moved the message, this is probably a simpler solution_

**Comment by Xiphe** [comment]
> I can find the text in Actions.tsx.

The text is in [src/app/components/Actions/Actions.tsx#L27-L30](https://github.com/mlevison/high-performance-teams-game/blob/main/src/app/components/Actions/Actions.tsx#L27-L30)

> What I can't see is how to add a mix of JavaScript/React to display the text.
> Is this reasonably easy?

I don't understand what you want to achieve here. The text is currently displayed. What would you like to be different?

> If not how would I suppress the message in the first round?

```diff
--- a/src/app/components/Actions/Actions.tsx
+++ b/src/app/components/Actions/Actions.tsx
@@ -23,12 +23,14 @@ export default function Actions(props: Props) {
   return (
     <>
       <h2>Available Actions</h2>
-      <p>
-        <em>
-          Previous rounds actions are still available, click the &#9658; to open
-          prior rounds.
-        </em>
-      </p>
+      {props.currentRound > 1 ? (
+        <p>
+          <em>
+            Previous rounds actions are still available, click the &#9658; to
+            open prior rounds.
+          </em>
+        </p>
+      ) : null}
       <p>
         Select Improvements or Actions that will affect the team. Once selected,
         the Actions cost will be deducted from the team's Working Capacity.
```

> _Now I've moved the message, this is probably a simpler solution_

Is this a statement? Where have you moved it, has it solved the issue?

**Comment by mlevison** [comment]
The original goal was to move the prompt below the current/open round so that the player's eye would drawn down and see the closed rounds. Given the way those are displayed I couldn't see a way of making that happen.

Actions.tsx - I was saying I could find the code. I just didn

**Comment by Xiphe** [comment]
Ah I understand now => https://github.com/mlevison/high-performance-teams-game/pull/130
