### ISSUE TITLE
Interruptions like Production Support - Special Effect Round N

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#14]
Teams that do nothing to protect themselves from interruption due to fires automatically lose half their capacity this round.
o Teams that pre-allocated time to deal with fires roll a die: 1-3 no additional losses; 4-5 lose one additional story; 6 lose two additional stories
o Teams that dedicated one sacrificial team member roll a die: 1-3 no additional stories lost – same outcomes pre-allocating time to deal with the fires
o Teams that pre-allocated capacity and sacrificed a team member, congratulations, you took care of all of the fires that came up.

"pre-allocated time" and "sacrificed a team member" are both special actions that are made available in the same round the interruptions occur. 

_The goal is to show teams that Production support work comes at a cost. Some of that cost can be mitigated if the team prepares for it_

**Comment by Xiphe** [comment]
Is there something actionable I can do here?

**Comment by mlevison** [comment]
Yes and it requires me to write something.

Basically in a round (5 or 6) after they've gone "live" the story will tell them that they might have prod support problems. The actions listed above will be the special actions for that round. Does this help?

**Comment by Xiphe** [comment]
I think whats irritating me is: "lose half their capacity -->this<-- round"
I think it makes for a strange UX if we modify the effects in the current round based on actions selected
I'd rather take the effects into next round (and assume it's meant this way ;))

**Comment by mlevison** [comment]
...this is on hold for a bit. We will do it after we fix some of usability stuff that is cropping up in early testing.

**Comment by mlevison** [comment]
ok and now I know how I want to handle these. Production support will simply be gremlin that can occur in round X and beyond. To make more likely I will assign it a 2 slots.

**Comment by mlevison** [comment]
Open questions:
- How to have a gremlin that occupies two die roll slots?
- How to have a gremlin that effects User Story success? I'm betting I just return: UserStoryChanceEffectProps instead of a Capacity Effect.
- How to have a gremlin skipped until a certain round? Example until product is live in the field there are no production support problems.

**Comment by Xiphe** [comment]
> How to have a gremlin that occupies two die roll slots?

You could move the implementation out of the list and assign it twice

```ts
const myGremlin: GremlinList[1] = {
  name: 'Management yells at a team member in public',
  description: <p>{/* ... */}</p>,
  effect(age, finishedActionIds) {
    return null;
  },
};
export const gremlins: GremlinList = {
  2: myGremlin,
  3: myGremlin,
};
```

But that would also make it so that the gremlin can appear twice (I use the roll [1+2 in this case]) to ignore future rolls.

You know that rolling two 6-sided dice has different probabilities for the numbers 2 - 12?
A `2` (similar `12`) has only one combination of dice rolls `1+1` (`6+6` for `12`)
While rolling `7` has the highest probability (`1+6`, `2+5`, 3+4` ...etc.)

So if you want a gremlin to appear more likely you can just put it closer to 7


> How to have a gremlin that effects User Story success? I'm betting I just return: UserStoryChanceEffectProps instead of a Capacity Effect.

correct, you can also return both: `{ userStoryChance: -10, capacityChange: -2 }`

> How to have a gremlin skipped until a certain round? Example until product is live in the field there are no production support problems.

currently not possible. Gremlins are hard-disabled until round 3 they currently don't have a handle on that.

**Comment by Xiphe** [comment]
Another idea how to implement this would be to use the round-description and a static random chance to change it's effect (and possibly description)

```ts
// kinda pseudo-code

/* basically pre-roll before the game starts */
const rng = Math.random();

export const round1: RoundDescription<never> = {
  effect(rounds) {
    if (concatByProp(rounds, 'selectedGameActionIds').includes('ACTION_PRE_ALLOCATE_TIME')) {
      return { capacityChange: rng > 0.5 ? -1 : -2 }
    }
    /* ... */
  }
};
```
