### ISSUE TITLE
Unique Gremlins & Test getGremlin selector

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#19]
1. I assume a gremlin can only occur once in the game right? @mlevison 
2. The logic wether or not a gremlin occurs or not is uncovered currently.

Follow up of https://github.com/mlevison/high-performance-teams-game/pull/12

**Comment by mlevison** [comment]
Each Gremlin can only occur once.
Only one Gremlin at a time.
---
The current implementation has an odd quirk that is my fault. The original design was roll a die (random number) -- then look up which gremlin was selected. As coded, it looks like it will be a die roll per gremlin until one sticks. 
The intention was only **one** die roll. If it selects nothing, then no effect. If it selects an already suffered gremlin no effect.

**Comment by Xiphe** [comment]
Current implementation works like this:

Starting round 3
 - Each Gremlins "occurs" method is invoked 
 - If multiple occur then one of them is selected randomly

So only one at a time but it can happen more than once.

I'll move it back to dice-rolling and make sure they only occur once in the game.

**Comment by mlevison** [comment]
The real difference is that the different version we created makes the likelihood of being hit by one each round slightly more likely.

**Comment by Xiphe** [comment]
Agree
