### ISSUE TITLE
Display which actions are new this round

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#2]
We need to be able show the actions which were new this round - this is important as the list of actions grow.

**Comment by Xiphe** [comment]
I agree. This is important. But also highly dependant on the UI.
Technically I can calculate the new ones from existing state.

**Comment by Xiphe** [comment]
Closing since the UI shows the actions in collapsable columns.

We're not showing when an action with missing dependencies from past rounds becomes selectable. If it user-tests indicate this would be helpful please re-open this.
