### ISSUE TITLE
images / emoji / only text

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#24]
Hey @mlevison in my current idea for the UI I wanted to add images for all game actions that are shown in thumbnail format when small and bigger on the detail view.

I'm pretty sure that this will make the overall UX much better by helping the players recognise the actions and their effects faster.

Thing is: You'd need to provide these pictures. I did a few searches on https://unsplash.com/ but haven't found good fits in short tie.

Another Idea would be to use Emoji 
- 🏗 Build Server
- 🏢 Team Members On SameFloor
- ⚠️  Unit Testing
...

Or we could just stick with plain text but then I'd need to rethink the UI a bit

--

What's your take on this?

**Comment by mlevison** [comment]
Images and icons are fundamentally a good idea. The challenge is only in the time and cost of implementation.

**Comment by mlevison** [comment]
images should be an attribute of the gameAction

**Comment by Xiphe** [comment]
> Images and icons are fundamentally a good idea. The challenge is only in the time and cost of implementation.

I second that. Technical Implementation is not complicated but you or your team would need to come up with fitting images

> images should be an attribute of the gameAction

I agree and that would be no problem. But I first wanted to check back with you if we should do the image thing.
- I'll now make the images customisable on the game action.
