### ISSUE TITLE
Action popup obsources Capacity calculation

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#26]
See: 
![](https://i.imgur.com/YeA4Fpg.png)

**Comment by Xiphe** [comment]
I agree, that now that's implemented it feels not good.

The Initial Idea in https://github.com/mlevison/high-performance-teams-game/issues/10 was to actually replace the capacity calculation with the action details. I went with this implementation to keep more context.

Do you have an idea how to better solve this?

If not, the next thing I'd try is to display the overlay directly under the selected action.

Also the overlay needs a close `X` button

**Comment by mlevison** [comment]
I think the capacity calculation you have provided does an excellent job. I think we take this to testing with users before we make changes. I would either move the popup: below the action or below all of the capacity calculation. I think being able to see the capacity calculation update immediately is very powerful.
