### ISSUE TITLE
Extend the game

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#3]
If we make the game 10-12 rounds long and spread the actions out over rounds then it will be easier to digest each round.

**Comment by Xiphe** [comment]
Sounds like a good thing to user-test

**Comment by mlevison** [comment]
Oddly I had this feedback from people playing the paper version. It was even in our first notes. However it got missed. FWIW this is more a placeholder for me. I simply need to map out roughly what I want and then change the code to match. I should be able to do this on my own.
