### ISSUE TITLE
Move gameActions, gameEffects, gremlins & roundDescriptions closer to each other

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#37]
Here's an architectural question @mlevison 

Currently we have the technical implementation AND the game specific configuration all in `src/state`.

With tech implementation I mean files like [`src/state/gameActions/getAvailableGameActions.ts`](https://github.com/mlevison/high-performance-teams-game/blob/29d8f5cbe1751e9697a05ef3c98dba4f4cc9c559/src/state/gameActions/getAvailableGameActions.ts)
With configuration I mean lists like [`src/state/gameActions/gameActions.ts#gameActionList`](https://github.com/mlevison/high-performance-teams-game/blob/main/src/state/gameActions/gameActions.ts#L19-L120)

I wonder if it would make more sense to move all these lists into a config folder next to state

```
src
┣ state
┃ ┣ gameActions/getAvailableGameActions.ts
┃ ┗ ...
┗ config
  ┣ gameActions.ts
  ┣ gameActions.spec.ts
  ┣ gremlins.ts
  ┣ gremlins.spec.ts
  ┗ ...
```

What do you think?

**Comment by mlevison** [comment]
Good idea - especially since I will likely want to change those files the most.

**Comment by Xiphe** [comment]
exactly. 👍
