### ISSUE TITLE
Results Page

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#38]
Follow up of https://github.com/mlevison/high-performance-teams-game/issues/10

---

We need a concept for the results page

What should be displayed there?

 - [x] Total user stories attempted+succeeded
 - [x] Log/review what happened in which round
 - [x] final capacity achieved
 - [x] replay button
 - [x] https://github.com/mlevison/high-performance-teams-game/issues/38

@mlevison could you describe the user story of the result screen?

**Comment by mlevison** [comment]
That would be a good start.

Also final capacity achieved.
