### ISSUE TITLE
Actions only last X rounds

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#4]
find a way to drop an action from the list 3 or 4 rounds after it was first introduced - I think I will need to limit the number of actions visible at one time to - 15? this means giving actions a maximum age - i.e. only display for X rounds.

I haven't decided what that limit is yet.

**Comment by Xiphe** [comment]
1. this can also be done using an [AvailabilityCheck](https://github.com/mlevison/high-performance-teams-game/blob/main/src/state/gameActions/types.ts#L12) 

2. I'd suggest to not care for this until we decided on a UI + notice the problem you're anticipating in the actual game

**Comment by Xiphe** [comment]
Closing since this seems not to be a problem with current UI.

@mlevison please reopen if you disagree
