### ISSUE TITLE
Implement effect on user story rolls

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#41]
Hey @mlevison 

There were some game actions that increased the chance to succeed in user stories (https://github.com/mlevison/high-performance-teams-game/commit/ae8021e385485acf36e8385b9e971d0635b14d85)

It shouldn't be too complicated to implement this to enable use like this

```ts
WORKING_AGREEMENTS: {
    name: 'Working Agreements',
    available: { round: 1 },
    description: 'Create Team Working Agreements',
    cost: 1,
    effect: () => ({ userStoryRollBonus: 1 }), // <-------
  },
```

let me know if I should add that. (or close this issue if not :))

---

### Acceptance Criteria

- [x] implemented as percentage
- [x] bonus effects are visible in the round outro

**Comment by mlevison** [comment]
Yes please add this.

**Comment by Xiphe** [comment]
while at it moving from dice-roll to percentage based (https://github.com/mlevison/high-performance-teams-game/issues/48)

Thus the `userStoryRollBonus` will be like `10` for "10%" bonus
