### ISSUE TITLE
Show Description Button should go away...

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#45]
From a user: "Show description by default,  I clicked the button thinking that it would give me more information but just is a rehash of the page before."

Instead just display the text.

**Comment by Xiphe** [comment]
To be clear: 

I'll remove the "show description" button and display the round description text and gremlins all the time?

Another Idea would be to convert it in a `◀ back` or `◀ back to round intro` button. That way the user will not expect new infos there and we'd still have less clutter in the actions view
