### ISSUE TITLE
remove cypress

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#5]
Since we're testing the game logic on a unit level, I'd suggest to remove the end-to-end tests because their coverage would overlap a lot.

I'd rather test the UI also in jest while mocking away the game logic.

Benefits I see:
- Less coverage overlap
- Simpler Setup
- Faster running tests

Do you agree @mlevison ?

**Comment by mlevison** [comment]
Yes - I just assume that you will be the one to rip it out not me - Mark
