### ISSUE TITLE
Instructions and Descriptive Text per round

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#6]
Each round will get special text - eg. “Team, welcome to the World’s Smallest Online Bookstore. We hired you because you’re the best individuals in your respective areas. Please remember that we’re Vulture Capital funded and we have only a few months runway, so you must deliver. This first Sprint, the company really needs you to prove that you can deliver a working ….”.

I understand that this is an html <p> tag - that's the easy part. Do I just jam the text into an array and look it up by round number?

**Comment by Xiphe** [comment]
> Do I just jam the text into an array and look it up by round number?

Yes, you could also create an array of JSX elements and look it up by number:

```jsx
const roundIntroTexts = [
  <>
    <h3>Team, welcome to the World’s Smallest Online Bookstore.</h3>
    <p>...</p>
  </>,
  <>
    <h3>Round 2...</h3>
    <p>...</p>
  </>,
];

export default function App() {
  const [state, dispatch] = useAppState();

  return (
    <>
      <h1>High-Performance Team Game </h1>
      {roundIntroTexts[state.currentRound.number - 1]}
   </>
  );
}
```

In #8 I also created an example how you could test this 
https://github.com/mlevison/high-performance-teams-game/pull/8/files#diff-019093a166dec3ee78d2905e3e30d50d549404ae799db66aa62058ec801dd5bb

**Comment by mlevison** [comment]
Understood - this item is effectively superseded by #7 where I noted that the text to describe the effect and effect itself should be bundled.

**Comment by Xiphe** [comment]
covered by #7
