### ISSUE TITLE
Working Agreements is affecting the User Story Success Die roll

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#62]
is that my intention? or is Protect the team from outside distraction?

**Comment by Xiphe** [comment]
I've got that from https://github.com/mlevison/high-performance-teams-game/commit/ae8021e385485acf36e8385b9e971d0635b14d85 - but that might have been a copy-paste command, I haven't checked back with the rules, sorry.

you can fix it here: https://github.com/mlevison/high-performance-teams-game/blob/main/src/config/rounds/round1.tsx#L68
