### ISSUE TITLE
Actions display

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#63]
I would like to change the selection colour from blue to green and make the line thicker to make it clear to the player that they have made a selection. I have no idea where to do that. _I should be skilled enough to do this_.

A player asked why we use a tooltip/popup to display the action description. He thinks displaying on the page would be better. I'm unsure.

**Comment by Xiphe** [comment]
highlight color: https://github.com/mlevison/high-performance-teams-game/blob/main/src/components/Actions/Actions.module.css#L74

thickness: https://github.com/mlevison/high-performance-teams-game/blob/main/src/components/Actions/Actions.module.css#L61

colors are used as css variables declared here: https://github.com/mlevison/high-performance-teams-game/blob/main/src/global.css#L1-L18


> A player asked why we use a tooltip/popup to display the action description. He thinks displaying on the page would be better. I'm unsure.

1. I think the UI is unscannable when we display all descriptions together
2. My first idea was to display the description at the place of the capacity breakdown when selected but we then decided that its benefitial to see that while reading the description.
3. While I don't like tooltips generally in this scenario I like that the rest of the UI does not jump
4. I generally don't think i'm an outstanding UI designer. The current implementation serves the purpose of "having a UI". And i'm really open to another approach

**Comment by mlevison** [comment]
Helpful. I've made some color changes.

>1.  I think the UI is unscannable when we display all descriptions together
>3. While I don't like tooltips generally in this scenario I like that the rest of the UI does not jump

So the question becomes - is there an elegant way to display the text only one action at a time? 
How about a dedicated - action description space/slot that displays the contents of the currently selected action?
Only one action at a time. Do we have space? 
If this doesn't work then we will shelve for later.

**Comment by Xiphe** [comment]
> How about a dedicated - action description space/slot that displays the contents of the currently selected action?

since the description itself is dynamic in size I don't think there is a good way to reserve space.

> Only one action at a time. Do we have space?

I don't understand

--- 

Not sure how much feedback you're getting for this but I'd keep this for later.
For product UI's overlays are generally a no-go but if you think games I cant come up with one that does NOT use overlays for something like descriptions etc.

**Comment by mlevison** [comment]
At this stage lets just close the item. If someone can sketch me a better idea later I will reconsider.
