### ISSUE TITLE
Gremlins

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#64]
A bunch of notes.
- It should say 'Gremlin' before when displayed. I would love to make that change myself but can't figure out where to.
- The gremlins affect on your capacity should be displayed when its text is display
- Gremlins that are in effect should remain displayed above the "Available Actions" list. This way people are reminded that gremlins are in effect.
- Gremlin's in the capacity calculation should be displayed with a highlight underneath them - perhaps some light red - to make the point that they're bad.
- Gremlins should from two die rolls to a percentage, then each gremlin will occupy a smaller or larger chunk of that percentage.

**Comment by Xiphe** [comment]
> It should say 'Gremlin' before when displayed. I would love to make that change myself but can't figure out where to.

the gremlin is displayed here: https://github.com/mlevison/high-performance-teams-game/blob/56b50ad8fb41f4044c234bad904b66d87249ee7b/src/components/Round.tsx#L68-L73

> Gremlins should [move?] from two die rolls to a percentage, then each gremlin will occupy a smaller or larger chunk of that percentage.

We had that and it caused problems 
- when each gremlin can occur at a percentage, then multiple can occur at the same time
- if we say 0-10% goes to gremlin1, 10-30% to gremlin2 thats basically a dice-roll

... I'll have a look at the other points

**Comment by mlevison** [comment]
Played with Gremlin text. Formatting should now make it obvious that is a gremlin.

I understand the problem percentages. I think I will eliminate the 2 x 6 sided die and replace with a single random from 1-> whatever we need. Likely I will make it 50% chance of hitting gremlin in any round.

**Comment by Xiphe** [comment]
With everything we know now it might make sense to move in this direction:

first roll IF a gremlin will appear (may be static 50/50 or based on some game modifier)

then give the gremlins an `probability` method where they can return a number based on current round, selected actions etc...

then do a second roll to pick one of the gremlins.

That way a gremlin could return `0` probability until it's precondition is met, it might become more likely over time etc. (ref https://github.com/mlevison/high-performance-teams-game/issues/14#issuecomment-734466627)

**Comment by mlevison** [comment]
Clever - yes this is a good direction assuming we're not talking about a large amount of work.

**Comment by Xiphe** [comment]
shouldn't be to complicated

**Comment by Xiphe** [comment]
There are some points open here right?

> - The gremlins affect on your capacity should be displayed when its text is display

Not sure if this will work reliably. I'll check


> - Gremlins that are in effect should remain displayed above the "Available Actions" list. This way people are reminded that gremlins are in effect.

Still valid?

> - Gremlin's in the capacity calculation should be displayed with a highlight underneath them - perhaps some light red - to make the point that they're bad.

Should we maybe underline each effect that has a negative capacity change?

**Comment by mlevison** [comment]
>>  The gremlins affect on your capacity should be displayed when its text is display
> Not sure if this will work reliably. I'll check

Ok - this is important because the text alone sounds ominous but doesn't tell them what will happen.

>> Gremlins that are in effect should remain displayed above the "Available Actions" list. This way people are reminded that gremlins are in effect.
> Still valid?

Yes

>> Gremlin's in the capacity calculation should be displayed with a highlight underneath them - perhaps some light red - to make the point that they're bad.
> Should we maybe underline each effect that has a negative capacity change?

Let's try.
