### ISSUE TITLE
Some rounds themselves have strange effects

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#7]
Example:

Round III – Sprint 7
“We must go live with an early version of the product this round, for CES. Due to your limited productivity in past rounds, management are prepared to offer some options to help you out. We will pay an extra ‘4’ points for anything that helps. Another team member? Overtime?”
-----

Round IV – Sprint 10
“We’re live, congratulations. In addition, if we’re unlucky some teams will have to deal with a fire.”

Facilitator’s notes
-	Teams that do nothing to protect themselves from interruption due to fires automatically lose half their capacity this round.
o	Teams that pre-allocated time to deal with fires roll a die: 1-3 no additional losses; 4-5 lose one additional story; 6 lose two additional stories
o	Teams that dedicated one sacrificial team member roll a die: 1-3 no additional stories lost – same outcomes pre-allocating time to deal with the fires
o	Teams that pre-allocated capacity and sacrificed a team member, congratulations, you took care of all of the fires that came up.
-	Teams that invested in Unit Testing two rounds ago gain 1 capacity.
-	Check to see if anyone gains benefits from Team Room; Social Time; Moving Desks closer together; Working Agreements;
----

These suggest that my idea of round description text in an array from the previous issue was a bad idea because it the association between the descriptive text and the effects should be clear.

**Comment by Xiphe** [comment]
I'm not able to wrap my head around this. 

I understand that round III has a special effect.

> We will pay an extra ‘4’ points for anything that helps

"Points" === "Capacity"? When does the team receive them?

> Teams that do nothing to protect themselves from interruption due to fires

How should we identify actions that protect from interruption?

> Teams that pre-allocated time

What does that mean in game terms? How can we detect the team pre-allocated time?

> Teams that dedicated one sacrificial team member

What does that mean in game terms? How can we detect the team dedicated a member?

> Check to see if anyone gains benefits from Team Room; Social Time; Moving Desks closer together; Working Agreements;

Then...?

---

Not sure if you've got an idea how to implement this or not. 

If you're able to I think it would help a lot if you could formulate user (as in the user playing the game) stories for this.
If not i suggest we talk in person.

**Comment by mlevison** [comment]
Hannes - on break now

On Tue, Nov 3, 2020 at 8:15 AM Hannes Diercks <notifications@github.com>
wrote:

> I'm not able to wrap my head around this.
>
> I understand that round III has a special effect.
>
> We will pay an extra ‘4’ points for anything that helps
>
> "Points" === "Capacity"? When does the team receive them?
>

Yes - points is the original language for the game. A better framing might
be this. "The CEO says we have a very important deadline coming up and we
will pay for overtime for the team for the next few weeks. That overtime is
the equivalent on increasing your capacity by 4 points. This increase is
for one round only and will go away after this round".

For now ignore all of the stuff below this, it's the setup text for the new
actions that would be available that round.

Thanks
- Mark

**Comment by Xiphe** [comment]
Still unsure what I should/could do as a fist step here. Lets talk in person.

**Comment by Xiphe** [comment]
based on what we discussed I'll just implement a way to add description text on a per round base. That can also come with an effect. (That would also cover #6)

Everything else will be split away by @mlevison and we'll care for that later.
