### ISSUE TITLE
UserStorySuccess change and Capacity change in one>

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#70]
The example isn't great, it does show something that would fun to simulate:
`PERSONAL_PRODUCTIVITY_BONUS: {
      image: example,
      name: 'Personal Productivity Bonus',
      description:
        'The company will offer anyone who exceeds their performance goals an extra $5,000. A manager says team members working harder will increase the likelihood of completing features on time',
      cost: 2,
      effect(age) {

        if (age > 1) {
          return {
          capacityChange : -1,
          userStoryChange : 0,
          title: "Productivity Bonus helped in the short term and then the benefit waned. Along the way it harmed collaboration";
          }
        }

        return {
          capacityChange : 0,
          userStoryChange : 50,
          title: "Productivity Bonus helped",
        };
      },
    },`

Both kinds of change at the same time. How difficult is this change?

**Comment by Xiphe** [comment]
The way you implemented it does not require two properties per return

```ts
if (age > 1) {
  return {
    capacityChange : -1,
    title: "Productivity Bonus helped in the short term and then the benefit waned. Along the way it harmed collaboration";
  }
};

return {
  userStoryChance : 50,
  title: "Productivity Bonus helped",
};
```

---

But nevertheless up until #71 this was possible

```
return {
  capacityChange : -1,
  userStoryChance : 50,
  title: "Productivity Bonus helped",
};
```

now, to prevent bugs we need to split that in two effects like

```ts
return [
{
  capacityChange : -1,
  title: "Productivity Bonus helped",
},
{
  userStoryChance : 50,
  title: EFFECT_HIDDEN
}
];
```

Not all `effect()` methods can return an array of effects. (IIRC only round and gremlin currently) I'll make sure it works everywhere.

**Comment by mlevison** [comment]
I tried this:
`effect(age) {
        if (age > 1) {
          return [
            {
              capacityChange: -1,
              title:
                'Productivity Bonus helped in the short term and then the benefit waned. Along the way it harmed collaboration',
            },
            {
              userStoryChance: 0,
              title: EFFECT_HIDDEN,
            },
          ];
        }

        return [
          {
            capacityChange: -1,
            title:
              'Productivity Bonus helped in the short term - team members focused on individual productivity',
          },
          {
            userStoryChange: 50,
            title: EFFECT_HIDDEN,
          },
        ];
      },
    },`

And still get a syntax error - that baffles my tiny brain: 
Type '(age: number) => ({ capacityChange: number; title: string; userStoryChance?: undefined; } | { userStoryChance: number; title: unique symbol; capacityChange?: undefined; })[] | ({ capacityChange: number; title: string; userStoryChange?: undefined; } | { ...; })[]' is not assignable to type '(age: number, finishedActionIds: GameActionId[]) => Effect[] | (Partial<VisibleEffectProps> & CapacityEffectProps) | ... 5 more ... | null'.
  Type '({ capacityChange: number; title: string; userStoryChance?: undefined; } | { userStoryChance: number; title: unique symbol; capacityChange?: undefined; })[] | ({ capacityChange: number; title: string; userStoryChange?: undefined; } | { ...; })[]' is not assignable to type 'Effect[] | (Partial<VisibleEffectProps> & CapacityEffectProps) | (Partial<VisibleEffectProps> & UserStoryChanceEffectProps) | ... 4 more ... | null'.
    Type '({ capacityChange: number; title: string; userStoryChange?: undefined; } | { userStoryChange: number; title: unique symbol; capacityChange?: undefined; })[]' is not assignable to type 'Effect[] | (Partial<VisibleEffectProps> & CapacityEffectProps) | (Partial<VisibleEffectProps> & UserStoryChanceEffectProps) | ... 4 more ... | null'.
      Type '({ capacityChange: number; title: string; userStoryChange?: undefined; } | { userStoryChange: number; title: unique symbol; capacityChange?: undefined; })[]' is not assignable to type 'Effect[]'.
        Type '{ capacityChange: number; title: string; userStoryChange?: undefined; } | { userStoryChange: number; title: unique symbol; capacityChange?: undefined; }' is not assignable to type 'Effect'.
          Type '{ userStoryChange: number; title: unique symbol; capacityChange?: undefined; }' is not assignable to type 'Effect'.
            Type '{ userStoryChange: number; title: unique symbol; capacityChange?: undefined; }' is not assignable to type 'GremlinChanceEffectProps & InvisibleEffectProps'.
              Property '[GREMLIN_CHANCE_KEY]' is missing in type '{ userStoryChange: number; title: unique symbol; capacityChange?: undefined; }' but required in type 'GremlinChanceEffectProps'.

**Comment by mlevison** [comment]
...this issue seems to have gotten lost - deep in your darkest inbox - Mark

**Comment by Xiphe** [comment]
on it now :)

**Comment by Xiphe** [comment]
The problem is caused by a typo. The effect prop is `userStoryChan-->c<--e` not `userStoryChange`.

I agree that the TS error is not helpful here. I found it by explicitly declaring the return type of the method.
`effect(age): Effect[] { /* ... */ }` that changed the error to only complain about the unknown property. 

I'll refactor all effect props to be `...Change` (ref https://github.com/mlevison/high-performance-teams-game/pull/67)
