### ISSUE TITLE
Actions and Gremlins need a field for us to display a more info link

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#80]
Since this is a game about learning - each gremlin and action should have slot for a link. My intention is to encourage the players to explore more depth behind each topic we cover. 

Unsurprisingly many of them of them will refer to material on the APR site :-)

**Comment by Xiphe** [comment]
The `description` of Actions, Rounds and Gremlins are `ReactElements` currently we only use a single Paragraph (`<p>`) for most, But you can add all other markup (and even custom components) in there.

```tsx
PROTECTED_FROM_OUTSIDE_DISTRACTION: {
  image: 'https://placekitten.com/100/100',
  name: 'Protected from Outside Distraction',
  description: (
    <>
      <p>
        <a href="https://example.org/what-is-a-scrum-master">ScrumMaster</a>{' '}
        protects the team from outside distraction. Example: A manager
        asking a team member to do them a small favour as it will only take
        an hour.
      </p>
      <p>Another Paragraph</p>
    </>
  ),
  cost: 1,
  effect: () => ({ userStoryChange: 10 }),
},
```

## Background:

The `<>{ /* <p>...</p> */}</>` wrapper is required to have one single parent element when declaring multiple JSX elements side-by-side
It's shorthand for `<React.Fragment>{ /* <p>...</p> */}</React.Fragment>` which is a special build-in component from react that will group it's children without adding additional elements to the DOM.
An alternative would be using `<div>{ /* <p>...</p> */}</div>`

**Comment by Xiphe** [comment]
It's generally considered good practise to have links on text itself rather than a general "more info" link.

Prefer `<a href="https://example.org/what-is-a-scrum-master">ScrumMaster</a> protects the team` over `ScrumMaster protects the team (<a href="https://example.org/what-is-a-scrum-master">more info</a>)`

That said, if you find yourself adding same-style "more info" links to the end of each description, lets rather add a `moreInfo` property to the action & gremlin config and add it there.

**Comment by Xiphe** [comment]
Would it maybe make sense to also allow links in effect descriptions?  ref https://github.com/mlevison/high-performance-teams-game/issues/58

**Comment by mlevison** [comment]
The big reason for a more info link as a separate thing is that it allows me to display More Info links and text (not naked links) in the end of game results. This way they finish a game and are intrigued. The save their game results and have the links to look up afterwards.

**Comment by Xiphe** [comment]
> The save their game results

THIS is new info for me. We never talked about the results being saveable :) ref https://github.com/mlevison/high-performance-teams-game/issues/81

**Comment by mlevison** [comment]
Not saveable. Any HTML page can be copy+pasted into a doc.

**Comment by Xiphe** [comment]
I see. So the requirement is everything is visible on one page so that it can be statically saved/copy-pasted

**Comment by mlevison** [comment]
I think that you might have achieved this with end of game log. Then its just a matter of me adding a link to more information in every description.
