### ISSUE TITLE
Should we simplify effect types to multi-purpose?

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#85]
> Why didn't we just always return a type with capacityChange, userStorySuccess and title?

The current composition type used for effects exists so that we can validate that an effect has exactly one of `gremlinChange`, `capacityChange` or `userStoryChange`.

If we change it to multi-purpose the type would allow the creation of an effect with only a title and no actual effect

```tsx
type Effect = {
  title: string;
  capacityChange?: number;
  gremlinChange?: number;
};

const myEffect: Effect = { title: 'hello' };
```

It also allows the creation of an effect that effects both: capacity and gremlin. (Which is what you're aiming at I figure)
But currently the game state logic assumes that effects only have one of each. 
For example `gremlinChange` and `userStoryChange` effects are treated differently because their effect is already active in the round they're selected. Using a multi-purpose effect would need refactoring of this logic.

So this is why it is this way. I see the benefits of using multi-purpose effects and assume the refactorings should be not to complicated.

**Comment by mlevison** [comment]
As former OO Developer I get lost in this world. Why use optionals? Why not just have a return type with title, capacityChange and userStoryChanceChange. The later two default to zero unless initialized.

**Comment by Xiphe** [comment]
> As former OO Developer I get lost in this world.

From my understanding this is not a problem specific to functional style.

> Why use optionals? Why not just have a return type with title, capacityChange and userStoryChanceChange. The later two default to zero unless initialized.

There is no difference between optionals and using defaults. 
Defaulting everything to zero would still allow the creation of an effect that only has a title and does not change anything in the game. I suspected that this is not intended and wanted to use the type-system to check this. Maybe I went to complicated.

---

As stated earlier I'm also not a fan of the status-quo and this issue mainly exists because you explicitly asked why it is the way it is.

I'll try to switch to multi-purpose effects that default to 0.

**Comment by Xiphe** [comment]
While refactoring I also found that having single-purpose effects made UI creation a lot easier. Because now each effect could potentially have multiple currencies that need to bee communicated to the user (for example in the log).

In reality I think there is no visible multi-value effect in the game but since it's not prevented by the type system anymore I would not like to just assume it stays this way.
