### ISSUE TITLE
Two axis charts improvement

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#91]
The existing two y axis charts are start. However its tough to distinguish the "percentage chance for user stories", from the other lines. Many times a bar chart combined with a line chart works better.

See this example:
![Two Axis Bar Chart](https://ubiq.co/blog/wp-content/uploads/2015/06/bar-line-chart.png)

Can we make the User Story Chance the bar element?

**Comment by Xiphe** [comment]
I'll see what's possible
