### ISSUE TITLE
Additional output from expect()?

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#92]
I tried looking in the Jest documentation and I can't find away. What I would like is expect().toBeEqual().AdditionalMessage(). The reason in attempting to debug:

```ts
export function testCurrentRound(
  game: ReturnType<typeof getGame>,
  round: BaseEffect,
) {
  if (round.userStoryChange !== undefined) {
    expect(game.state.currentRound.userStoryChance).toEqual(
      round.userStoryChange + START_USER_STORY_CHANCE,
    );
  }
  if (round.capacityChange !== undefined) {
    expect(game.state.currentRound.capacity.total).toEqual(
      round.capacityChange + START_CAPACITY,
    );
  }
  if (round.gremlinChange !== undefined) {
    expect(game.state.currentRound.gremlinChance).toEqual(
      round.gremlinChange + START_GREMLIN_CHANCE,
    );
  }
}
```

Being able to use an additional message function, I would use it to spit out enough information about the the current round to understand what is happening at that moment.

**Comment by Xiphe** [comment]
I also don't know if there is a good `expect` api for this.

What should be possible is

```ts
try {
  expect(something).toEqual(somethingElse);
} catch (err) {
  throw new Error('My custom error message');
}
```

But I have not used this.
I'd personally try to not build to complex test helpers that need additional explanation.
If you'd made the expectation directly in you test you should be able to debug it more easily.

Or you could create a custom matcher (https://jestjs.io/docs/en/expect#expectextendmatchers)

**Comment by mlevison** [comment]
I guess I create a customer matcher. The functions exist to reduce the volume of boilerplate code when writing test cases so I don't want to go backward from there.

**Comment by mlevison** [comment]
I've spent chunks of time during the workshop day attempting to create a matcher. I have failed. I can copy and past the matcher from the jest docs: https://jestjs.io/docs/en/expect
`expect.extend({
  toBeWithinRange(received, floor, ceiling) {
    const pass = received >= floor && received <= ceiling;
    if (pass) {
      return {
        message: () =>
          `expected ${received} not to be within range ${floor} - ${ceiling}`,
        pass: true,
      };
    } else {
      return {
        message: () =>
          `expected ${received} to be within range ${floor} - ${ceiling}`,
        pass: false,
      };
    }
  },
});`

It has no problem in being declared. However then I can't call it.
`expect(1).toBeWithinRange(0, 3);`

gets the message: Property 'toBeWithinRange' does not exist on type 'JestMatchersShape<Matchers<void, number>, Matchers<Promise<void>, number>>'.

Of course I really want to call my own method
`expect.extend({
  changeEquality(received, expected, round, message) {
    if (received === expected) {
      return {
        message: () => `test passed no message`,
        pass: true,
      };
    } else {
      return {
        message: () =>
          `${message} Expected ${expected} to equal to ${received} round ${round}`,
        pass: false,
      };
    }
  },
});`

But it fails for the same reason.

How am I failing as member of humanity?

**Comment by Xiphe** [comment]
> gets the message: Property 'toBeWithinRange' does not exist on type 'JestMatchersShape<Matchers<void, number>, Matchers<Promise, number>>'.

You're not failing Marc, It's typescript not being smart enough to know that you've globally extended the expect object.


Quoting from https://jestjs.io/docs/en/expect:

> Note: In TypeScript, when using @types/jest for example, you can declare the new toBeWithinRange matcher like this:
> ```
> declare global {
>  namespace jest {
>    interface Matchers<R> {
>      toBeWithinRange(a: number, b: number): R;
>    }
>  }
> }
> ```
